# Generated by Django 2.1.4 on 2019-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20190312_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location_map',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
